Config = Config or {}

Config.DutyActions = {
    ['Dispatch'] = "Dispatch",
    ['Police'] = "Police",
    ['StoreSecurity'] = "Store Cooperation",
    ['EMS'] = "EMS",
    ['DOC'] = "DOC",
    -- ['lawyer'] = "Lawyer",
    ['judge'] = "Judge",
}

Config.AlertBlip = {
    ['Officer Injured'] = 429,
    ['Officer Injured URGENT'] = 437,
    ['Bolingbroke Penitentiary Alarm'] = 189,
    ['Ambulance Injured'] = 429,
    ['Ambulance Injured URGENT'] = 437,
    ['Panic Button'] = 487,
    ['Shots Fired from Vehicle'] = 229,
    ['Shots Fired'] = 313,
    ['Fight in Progress'] = 311,
    ['Deadly Fight in Progress'] = 154,
    ['Injured Civilian'] = 621,
    ['Jewelry Store Alarm'] = 617,
    ['House Alarm'] = 40,
    ['Bank Truck Alarm'] = 477,
    ['Explosion'] = 486,
    ['Prison Alarm'] = 188,
    ['Illegal Hunting'] = 442,
    ['Anonymous 911 Call'] = 817,
    ['911 Call'] = 817,
    ['Ammunation Alarm'] = 110,
    ['Vehicle Theft'] = 811,
    ['Business Alarm'] = 487,
    ['Fleeca Bank Alarm'] = 354,
    ['Bay City Bank Alarm'] = 354,
    ['Bobcat Security Alarm'] = 354,
    ['Blaine County Savings Bank Alarm'] = 354,
    ['City Vault Alarm'] = 618,
    ['Controlled Account Activity'] = 272,
    ['Goods Tracker Manipulation'] = 466,
    ['Container Security System Manipulation'] = 50,
    ['Person Robbery in Progress'] = 362,
}